export { buildDedupeKey, isDuplicatePlanItem } from "./plan/planDedupe";
export type { PlanDedupeInput } from "./plan/planDedupe";
export { planFromGuide } from './plan/planFromGuide';
export type { GuidePlanInput } from './plan/planFromGuide';
export { calculatePlanProgress } from "./plan/planProgress";
export { buildVisaPolicyKey, matchVisaPolicy, getVisaFreshness } from "./visa/visaPolicy";
export { sortTripDestinations } from "./trip/tripDestination";
export { getCurrentTripStage, canTransitionTripStatus } from "./trip/tripStage";
export { getStageSwitchPrompt } from './trip/tripStageSwitch';
export type { StageSwitchPrompt } from './trip/tripStageSwitch';
export { groupTravelLegs } from './destination/grouping';
export { diffContentVersion } from "./content/contentVersion";
